// Generated by CoffeeScript 1.10.0
(function() {
  var Parser, ancestorNode, colorEncode, inferAncestorNode, insertNewLines, parser, removeBlockquotes;

  Parser = (function() {
    function Parser(content) {
      this.content = content;
      this.state = 'init';
    }

    Parser.prototype.cleanIndentation = function() {
      var cleanedLines, j, len, line, lines;
      this.state = 'cleanIndentation';
      lines = this.content.split(/\r?\n/);
      cleanedLines = [];
      for (j = 0, len = lines.length; j < len; j++) {
        line = lines[j];
        cleanedLines.push(line.trim().replace(/^(?:>\s*){1,}/, "").trim());
      }
      this.content = cleanedLines.join("\n");
      return this;
    };

    Parser.prototype.stripFromToBlocks = function() {
      var blockRegex, replacer;
      this.state = 'stripFromToBlocks';
      blockRegex = /From:[\s\S]*?(To|Subject|Date|Cc|Sent):[\s\S]*?(To|Subject|Date|Cc|Sent):[\s\S]*?(To|Subject|Date|Cc|Sent):[\s\S]*?(To|Subject|Date|Cc|Sent):(.*\n){1,2}/g;
      replacer = (function(_this) {
        return function(match, offset, string) {
          var date, from;
          match = match.replace(/\r?\n/g, " ");
          from = (/From:(.*?)(To|Subject|Date|Cc|Sent):/g.exec(match))[1].trim();
          date = (/(Date|Sent):(.*?)(To|Subject|Cc):/g.exec(match))[2].trim();
          return "On " + date + ", " + from + " wrote:\n\n";
        };
      })(this);
      this.content = this.content.replace(blockRegex, replacer);
      return this;
    };

    Parser.prototype.toMarkdown = function() {
      var replacer;
      this.state = 'toMarkdown';
      this.content = this.content.replace(/(#)/g, "\\$1");
      replacer = (function(_this) {
        return function(match, offset, string) {
          var emailRegex;
          match = match.replace(/\r?\n/g, " ");
          match = match.replace(/([\[\]<>]|mailto:|javascript:;)/g, "");
          emailRegex = /([a-zA-Z0-9_!#$%&'*+\/=?`{|}~^.-]+@[a-zA-Z0-9.-]+)/;
          match = match.replace(emailRegex, "[$1](mailto:$1)");
          return "\n# " + match + "\n";
        };
      })(this);
      this.content = this.content.replace(/On [\s\S]*?wrote(:|;)/g, replacer);
      return this;
    };

    Parser.prototype.toHTML = function() {
      var el, i, j, len, outputTree, parsedTree, ref;
      this.state = 'toHTML';
      parsedTree = markdown.toHTMLTree(markdown.parse(this.content));
      outputTree = [parsedTree[0], ["div"]];
      i = 1;
      ref = parsedTree.slice(1);
      for (j = 0, len = ref.length; j < len; j++) {
        el = ref[j];
        if (el[0] === "h1") {
          outputTree.push(["div"]);
          i += 1;
        }
        outputTree[i].push(el);
      }
      this.content = markdown.renderJsonML(outputTree);
      return this;
    };

    Parser.prototype.log = function() {
      console.log([this.state, this.content].join(":"));
      return this;
    };

    return Parser;

  })();

  inferAncestorNode = (function(_this) {
    return function() {
      var ancestor, blockquotes;
      blockquotes = document.body.getElementsByTagName("blockquote");
      if (blockquotes.length > 0) {
        ancestor = blockquotes[0].parentNode;
      }
      if ((ancestor != null)) {
        return ancestor;
      } else {
        return null;
      }
    };
  })(this);

  insertNewLines = (function(_this) {
    return function(node) {
      var div, divs, j, k, len, len1, results, span, spans;
      divs = node.getElementsByTagName("div");
      for (j = 0, len = divs.length; j < len; j++) {
        div = divs[j];
        div.appendChild(document.createTextNode("\n\n"));
      }
      spans = node.getElementsByTagName("span");
      results = [];
      for (k = 0, len1 = spans.length; k < len1; k++) {
        span = spans[k];
        results.push(span.appendChild(document.createTextNode("\n\n")));
      }
      return results;
    };
  })(this);

  removeBlockquotes = (function(_this) {
    return function(node) {
      var blockquotes, bq, bqHtml, newChild, parent, results;
      blockquotes = node.getElementsByTagName("blockquote");
      results = [];
      while (blockquotes.length > 0) {
        bq = blockquotes[0];
        bqHtml = bq.innerHTML;
        parent = bq.parentNode;
        newChild = document.createElement("p");
        newChild.insertAdjacentHTML('afterbegin', bqHtml);
        parent.insertBefore(newChild, bq);
        parent.removeChild(bq);
        results.push(blockquotes = node.getElementsByTagName("blockquote"));
      }
      return results;
    };
  })(this);

  colorEncode = (function(_this) {
    return function(node) {
      var cl, clStyle, classes, colors, div, divs, i, j, k, len, len1, results, style;
      divs = node.getElementsByTagName("div");
      classes = ['first', 'second'];
      for (i = j = 0, len = divs.length; j < len; i = ++j) {
        div = divs[i];
        div.className = classes[i % 2];
      }
      style = document.createElement("style");
      style.appendChild(document.createTextNode(""));
      document.head.appendChild(style);
      style.sheet.insertRule("h1 { margin-bottom: 4px; font-size: 15px; font-family: Georgia,'Times New Roman','Bitstream Charter',Times,serif; }", 0);
      style.sheet.insertRule("p { margin: 2px; font-size: 15px; font-family: Arial,'Bitstream Vera Sans',Helvetica,Verdana,sans-serif; }", 0);
      style.sheet.insertRule("div { margin: 2px; }", 0);
      colors = ['#D3D3D3', '#A9A9A9'];
      results = [];
      for (i = k = 0, len1 = classes.length; k < len1; i = ++k) {
        cl = classes[i];
        clStyle = "." + cl + " { display: block; background-color: " + colors[i] + "; }";
        results.push(style.sheet.insertRule(clStyle, 0));
      }
      return results;
    };
  })(this);

  ancestorNode = inferAncestorNode();

  if (ancestorNode !== null) {
    insertNewLines(ancestorNode);
    removeBlockquotes(ancestorNode);
    parser = new Parser(ancestorNode.textContent);
    ancestorNode.innerHTML = parser.cleanIndentation().stripFromToBlocks().toMarkdown().toHTML().content;
  }

}).call(this);
