// Generated by CoffeeScript 1.10.0
(function() {
  var cleanIndentation, htmlContent, reindented, textContent;

  cleanIndentation = (function(_this) {
    return function(text) {
      var cleanedLines, i, len, line, lines;
      lines = text.split("\n");
      cleanedLines = [];
      for (i = 0, len = lines.length; i < len; i++) {
        line = lines[i];
        cleanedLines.push(line.trim().replace(/^(?:>\s*){1,}/, "").trim());
      }
      return cleanedLines.join("\n");
    };
  })(this);

  textContent = document.body.textContent;

  reindented = cleanIndentation(textContent);

  htmlContent = markdown.toHTML(reindented);

  document.body.innerHTML = htmlContent;

}).call(this);
